"use client";

import { useEffect, useRef, useState } from "react";
import type { CSSProperties, FormEvent } from "react";

const API_BASE = "http://127.0.0.1:8000";
const INITIAL_DOCUMENT_ID = "bccb14bb-f26f-4996-924a-e182105acf11";

type CoverageStatus =
  | "covered"
  | "drafts_pending_review"
  | "rejected_only"
  | "no_tests";

type RequirementCoverage = {
  document_id: string;
  requirement_id: string;
  text: string;
  source_line: number;
  coverage_status: CoverageStatus;
  covered: boolean;
  test_case_count: number;
  approved_test_count: number;
  draft_test_count: number;
  rejected_test_count: number;
  test_case_ids: string[];
};

type CoverageResponse = {
  document_id: string;
  title: string;
  coverage_basis: string;
  coverage_scope: string;
  requirement_count: number;
  covered_requirement_count: number;
  uncovered_requirement_count: number;
  coverage_percentage: number | null;
  status_counts: Record<CoverageStatus, number>;
  requirements: RequirementCoverage[];
};

type TestCaseContent = {
  title: string;
  preconditions: string[];
  test_data: string[];
  steps: string[];
  expected_result: string;
  assumptions: string[];
  document_id: string;
  requirement_id: string;
};

type SavedTestCase = {
  test_case_id: string;
  document_id: string;
  requirement_id: string;
  status: "draft" | "approved" | "rejected";
  saved: boolean;
  origin: string;
  created_at: string;
  test_case: TestCaseContent;
  requirement_snapshot: {
    document_id: string;
    requirement_id: string;
    text: string;
    source_line: number;
    source_text: string;
    created_at: string;
    filename?: string | null;
    page?: number | null;
    source_page_line?: number | null;
  };
  review: {
    decision: "approved" | "rejected";
    note: string;
    reviewed_at: string;
  } | null;
};

type GeneratedDraft = {
  document_id: string;
  requirement_id: string;
  model: string;
  status: "draft";
  saved: false;
  structured_validation: boolean;
  validation_scope: string;
  test_case: TestCaseContent;
  target_requirement: SavedTestCase["requirement_snapshot"];
};

function DetailList({ title, items, ordered = false }: { title: string; items: string[]; ordered?: boolean }) {
  const List = ordered ? "ol" : "ul";
  return (
    <div style={{ marginTop: "18px" }}>
      <h5 style={{ fontSize: "14px", fontWeight: 700, marginBottom: "8px" }}>{title}</h5>
      {items.length ? (
        <List style={{ paddingLeft: "22px", listStyleType: ordered ? "decimal" : "disc", lineHeight: 1.7 }}>
          {items.map((item, index) => <li key={index} style={{ marginBottom: "5px", overflowWrap: "anywhere" }}>{item}</li>)}
        </List>
      ) : <p style={{ color: "#596779" }}>None recorded.</p>}
    </div>
  );
}

function TestDetails({ record, documentTitle, onUpdated, onReviewed }: { record: SavedTestCase | GeneratedDraft; documentTitle: string; onUpdated?: (record: SavedTestCase) => void; onReviewed?: (record: SavedTestCase) => void }) {
  const snapshot = "requirement_snapshot" in record ? record.requirement_snapshot : record.target_requirement;
  const review = "review" in record ? record.review : null;
  const colors = record.status === "approved"
    ? statusColors.covered
    : record.status === "rejected"
      ? statusColors.rejected_only
      : statusColors.drafts_pending_review;
  return (
    <article style={{ marginTop: "18px", padding: "22px", border: "1px solid #e0e6ed", borderRadius: "12px", background: "#ffffff" }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: "12px", flexWrap: "wrap" }}>
        <h4 style={{ fontSize: "19px", fontWeight: 700 }}>{record.test_case.title}</h4>
        <span style={{ ...colors, padding: "6px 10px", borderRadius: "6px", fontSize: "13px", fontWeight: 600 }}>
          {record.status === "approved" ? "Approved" : record.status === "rejected" ? "Rejected" : record.saved ? "Draft" : "Unsaved draft"}
        </span>
      </div>
      <p style={{ marginTop: "8px", color: "#596779", fontSize: "12px", overflowWrap: "anywhere" }}>
        {"test_case_id" in record ? `Test case ID: ${record.test_case_id}` : `Generated by ${record.model}. Not saved or reviewed.`}
      </p>
      <div style={{ display: "flex", gap: "24px", flexWrap: "wrap", marginTop: "20px", fontSize: "14px" }}>
        <div style={{ flex: "2 1 340px", minWidth: 0 }}>
          <DetailList title="Preconditions" items={record.test_case.preconditions} />
          <DetailList title="Test data" items={record.test_case.test_data} />
          <DetailList title="Steps" items={record.test_case.steps} ordered />
          <h5 style={{ fontSize: "14px", fontWeight: 700, margin: "18px 0 8px" }}>Expected result</h5>
          <p style={{ lineHeight: 1.7, overflowWrap: "anywhere" }}>{record.test_case.expected_result}</p>
          <DetailList title="Assumptions" items={record.test_case.assumptions} />
        </div>
        <aside style={{ flex: "1 1 260px", minWidth: 0, padding: "18px", borderRadius: "10px", background: "#f3f6fa", alignSelf: "flex-start" }}>
          <h5 style={{ fontSize: "15px", fontWeight: 700, marginBottom: "14px" }}>Source requirement</h5>
          <p style={{ marginBottom: "8px" }}><strong>Document:</strong> {documentTitle}</p>
          <p style={{ marginBottom: "8px" }}><strong>Requirement:</strong> {snapshot.requirement_id}</p>
          {snapshot.filename && (
            <p style={{ marginBottom: "8px", overflowWrap: "anywhere" }}><strong>PDF file:</strong> {snapshot.filename}</p>
          )}
          {snapshot.page != null && (
            <p style={{ marginBottom: "8px" }}><strong>PDF page:</strong> {snapshot.page}</p>
          )}
          {snapshot.source_page_line != null && (
            <p style={{ marginBottom: "8px" }}><strong>Line within page:</strong> {snapshot.source_page_line}</p>
          )}
          <p style={{ marginBottom: "12px" }}><strong>{snapshot.filename ? "Document text line:" : "Source line:"}</strong> {snapshot.source_line}</p>
          <blockquote style={{ margin: "0", padding: "12px", borderLeft: "3px solid #24634f", background: "#ffffff", lineHeight: 1.7, whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>
            {snapshot.source_text}
          </blockquote>
          <p style={{ marginTop: "12px", color: "#596779", fontSize: "12px", lineHeight: 1.6 }}>
            {record.saved ? "This is the requirement snapshot stored when the test was saved." : "This is the exact target requirement supplied to the model."}
            {" "}The link identifies its intended source; it does not verify every generated detail.
          </p>
          <p style={{ marginTop: "12px", fontSize: "12px", overflowWrap: "anywhere" }}><strong>Document ID:</strong> {snapshot.document_id}</p>
          <h5 style={{ fontSize: "15px", fontWeight: 700, margin: "22px 0 10px" }}>Review</h5>
          {review ? (
            <>
              <p style={{ lineHeight: 1.7, whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{review.note}</p>
              <p style={{ marginTop: "10px", color: "#596779", fontSize: "12px" }}>
                Reviewed: {new Date(review.reviewed_at).toLocaleString()}
              </p>
            </>
          ) : <p style={{ color: "#596779" }}>{record.saved ? "This draft has not been reviewed." : "Save and review this draft before treating it as an approved test."}</p>}
          <p style={{ marginTop: "16px", color: "#596779", fontSize: "12px", lineHeight: 1.6 }}>
            Approval concerns test design. No test execution result is recorded here.
          </p>
        </aside>
      </div>
      {"test_case_id" in record && record.status === "draft" && onUpdated && (
        <DraftEditor record={record} onUpdated={onUpdated} onReviewed={onReviewed} />
      )}
    </article>
  );
}

type RequirementsDocument = {
  document_id: string;
  title: string;
  text: string;
  characters: number;
  created_at: string;
};

type UploadedPdf = RequirementsDocument & {
  saved: true;
  filename: string;
  source_type: "pdf";
  page_count: number;
  original_file_saved: boolean;
  source_characters: number;
  requirements_extracted: boolean;
  requirements_indexed: boolean;
  pdf_search_indexed: boolean;
  pdf_search_index_status: string;
  warnings: string[];
  page_details: {
    page: number;
    text: string;
    characters: number;
    has_text: boolean;
    document_line_start: number | null;
    document_line_end: number | null;
  }[];
};

function RequirementsEntry() {
  const [method, setMethod] = useState<"pdf" | "manual" | null>(null);
  const options = [
    { value: "pdf" as const, title: "Upload PDF", description: "Use an existing requirements document. Keep its filename and page references.", panelId: "pdf-entry-panel" },
    { value: "manual" as const, title: "Enter manually", description: "Type or paste requirements and give your source document a title.", panelId: "manual-entry-panel" },
  ];

  return (
    <section aria-labelledby="requirements-entry-heading" style={{ marginBottom: "24px" }}>
      <div style={{ padding: "22px", border: "1px solid #e0e6ed", borderRadius: "12px", background: "#ffffff", marginBottom: "16px" }}>
        <h2 id="requirements-entry-heading" style={{ fontSize: "22px", fontWeight: 700 }}>Add requirements</h2>
        <p style={{ margin: "10px 0 18px", fontSize: "14px", color: "#596779", lineHeight: 1.6 }}>
          Choose how you want to provide your requirements.
        </p>
        <div role="group" aria-label="Requirements input method" style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "14px" }}>
          {options.map((option) => {
            const selected = method === option.value;
            return (
              <button key={option.value} type="button" aria-pressed={selected} aria-controls={option.panelId}
                onClick={() => setMethod(option.value)}
                style={{ textAlign: "left", padding: "18px", border: `2px solid ${selected ? "#24634f" : "#dce3eb"}`, borderRadius: "10px", background: selected ? "#edf7f2" : "#ffffff", color: "#1c293b", cursor: "pointer", fontFamily: "inherit" }}>
                <span style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", fontSize: "16px", fontWeight: 700 }}>
                  {option.title}
                  {selected && <span style={{ fontSize: "12px", fontWeight: 600, color: "#17623b" }}>Selected</span>}
                </span>
                <span style={{ display: "block", marginTop: "9px", fontSize: "13px", lineHeight: 1.6, color: "#596779" }}>{option.description}</span>
              </button>
            );
          })}
        </div>
        <p role="status" style={{ marginTop: "14px", fontSize: "13px", color: "#596779", lineHeight: 1.6 }}>
          {method === null ? "Select an option above to begin." : method === "pdf" ? "Upload your PDF using the form below. A document title is assigned from the filename." : "Enter a title and your requirements using the form below. No file upload is needed."}
        </p>
      </div>
      {/* Keep both forms mounted so changing methods preserves input and saved results. */}
      <div id="pdf-entry-panel" hidden={method !== "pdf"}><PdfUploadForm /></div>
      <div id="manual-entry-panel" hidden={method !== "manual"}><RequirementsInputForm /></div>
    </section>
  );
}

type PreviewRequirement = {
  document_id: string;
  requirement_id: string;
  text: string;
  source_text: string;
  source_line: number;
  filename?: string;
  page?: number;
  source_page_line?: number;
};

type RequirementsPreviewResponse = {
  document_id: string;
  title: string;
  extraction_method: "non_empty_lines";
  preview_only: true;
  requirement_count: number;
  requirements: PreviewRequirement[];
  warnings?: string[];
};

function RequirementsPreview({ documentId }: { documentId: string }) {
  const [preview, setPreview] = useState<RequirementsPreviewResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const controllerRef = useRef<AbortController | null>(null);

  useEffect(() => {
    setPreview(null);
    setError(null);
    setLoading(false);
    return () => {
      controllerRef.current?.abort();
      controllerRef.current = null;
    };
  }, [documentId]);

  async function loadPreview() {
    if (controllerRef.current) return;
    const controller = new AbortController();
    controllerRef.current = controller;
    setLoading(true);
    setError(null);
    setPreview(null);
    try {
      const response = await fetch(
        `${API_BASE}/requirements/documents/${encodeURIComponent(documentId)}/requirements/preview`,
        { method: "GET", cache: "no-store", signal: controller.signal },
      );
      if (!response.ok) {
        let message = `Preview failed (HTTP ${response.status}).`;
        try {
          const body = await response.json();
          if (typeof body.detail === "string") message = body.detail;
        } catch { /* Keep the HTTP message. */ }
        throw new Error(message);
      }
      const result: RequirementsPreviewResponse = await response.json();
      if (result.document_id !== documentId || result.preview_only !== true ||
        result.extraction_method !== "non_empty_lines" || typeof result.title !== "string" ||
        !Array.isArray(result.requirements) || result.requirement_count !== result.requirements.length ||
        !result.requirements.every((item) => item && item.document_id === documentId &&
          typeof item.requirement_id === "string" && typeof item.text === "string" &&
          typeof item.source_text === "string" && Number.isInteger(item.source_line) && item.source_line > 0) ||
        (result.warnings !== undefined && (!Array.isArray(result.warnings) ||
          !result.warnings.every((warning) => typeof warning === "string")))) {
        throw new Error("The backend returned incomplete or mismatched preview details.");
      }
      if (!controller.signal.aborted) setPreview(result);
    } catch (caught) {
      if (!controller.signal.aborted) setError(caught instanceof TypeError
        ? "Could not connect to the backend. Check that it is running, then retry the preview."
        : caught instanceof Error ? caught.message : "Unable to preview requirements.");
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null;
        if (!controller.signal.aborted) setLoading(false);
      }
    }
  }

  return (
    <section aria-label="Requirements preview" style={{ marginTop: "20px", padding: "18px", border: "1px solid #e0e6ed", borderRadius: "10px", background: "#ffffff" }}>
      <h3 style={{ fontSize: "18px", fontWeight: 700 }}>Preview requirements</h3>
      <p style={{ marginTop: "10px", fontSize: "13px", lineHeight: 1.6, color: "#596779" }}>
        Check the candidate requirements before saving them. Currently, each non-empty document line
        becomes one candidate; headings or wrapped sentences may need review.
      </p>
      <button type="button" onClick={() => void loadPreview()} disabled={loading}
        style={{ ...buttonStyle, marginTop: "14px", opacity: loading ? 0.6 : 1 }}>
        {loading ? "Loading preview..." : preview ? "Refresh preview" : "Preview requirements"}
      </button>
      {loading && <p role="status" style={{ marginTop: "12px", fontSize: "13px" }}>Reading requirements from the saved document...</p>}
      {error && <p role="alert" style={{ marginTop: "14px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{error}</p>}
      {preview && (
        <div style={{ marginTop: "18px" }}>
          <p style={{ fontWeight: 600 }}>{preview.title}</p>
          <p style={{ marginTop: "8px", fontSize: "13px", overflowWrap: "anywhere" }}>Document ID: {preview.document_id}</p>
          <p role="status" style={{ marginTop: "12px", color: "#17623b", fontSize: "14px" }}>
            {preview.requirement_count} candidate requirements found. Preview only — no requirements saved or indexed by this action.
          </p>
          {(preview.warnings ?? []).map((warning, index) => (
            <p key={index} style={{ marginTop: "12px", padding: "12px", background: "#fff3d6", color: "#765300", borderRadius: "8px" }}>{warning}</p>
          ))}
          {preview.requirements.length === 0 ? (
            <p style={{ marginTop: "14px", fontSize: "14px" }}>No non-empty requirement lines were found.</p>
          ) : (
            <div style={{ marginTop: "16px", overflowX: "auto" }}>
              <table style={{ width: "100%", minWidth: "600px", borderCollapse: "collapse", fontSize: "14px" }}>
                <thead style={{ background: "#edf2f7" }}>
                  <tr>{["Candidate ID", "Requirement", "Source"].map((heading) => <th key={heading} scope="col" style={{ ...cellStyle, fontWeight: 600 }}>{heading}</th>)}</tr>
                </thead>
                <tbody>
                  {preview.requirements.map((item) => (
                    <tr key={`${item.document_id}:${item.requirement_id}`}>
                      <th scope="row" style={{ ...cellStyle, whiteSpace: "nowrap" }}>{item.requirement_id}</th>
                      <td style={{ ...cellStyle, lineHeight: 1.6, minWidth: "240px" }}>
                        {item.text}
                        <details style={{ marginTop: "10px", fontSize: "12px", color: "#596779" }}>
                          <summary style={{ cursor: "pointer" }}>Original source text</summary>
                          <p style={{ marginTop: "8px", whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{item.source_text}</p>
                        </details>
                      </td>
                      <td style={{ ...cellStyle, fontSize: "12px", lineHeight: 1.7, overflowWrap: "anywhere" }}>
                        {item.filename && <div>{item.filename}</div>}
                        {item.page != null && <div>Page {item.page}</div>}
                        {item.source_page_line != null && <div>Page line {item.source_page_line}</div>}
                        <div>Document line {item.source_line}</div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
          <p style={{ marginTop: "14px", fontSize: "13px", color: "#596779", lineHeight: 1.6 }}>
            Saving these requirements and indexing them will be the next steps before test-case generation.
          </p>
        </div>
      )}
    </section>
  );
}

function PdfUploadForm() {
  const [file, setFile] = useState<File | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploaded, setUploaded] = useState<UploadedPdf | null>(null);
  const [error, setError] = useState<string | null>(null);
  const controllerRef = useRef<AbortController | null>(null);
  useEffect(() => () => controllerRef.current?.abort(), []);

  async function uploadPdf(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!file || uploaded || controllerRef.current) return;
    setError(null);
    if (!file.name.toLowerCase().endsWith(".pdf") || file.size === 0 || file.size > 10 * 1024 * 1024) {
      setError("Choose a non-empty PDF file of 10 MB or less.");
      return;
    }
    const controller = new AbortController();
    controllerRef.current = controller;
    setUploading(true);
    const formData = new FormData();
    formData.append("file", file);
    try {
      const response = await fetch(`${API_BASE}/upload-pdf`, {
        method: "POST",
        body: formData,
        // Let the browser set the multipart boundary and Content-Type.
        signal: controller.signal,
      });
      if (!response.ok) {
        let message = `Upload failed (HTTP ${response.status}).`;
        try {
          const body = await response.json();
          if (typeof body.detail === "string") message = body.detail;
          else if (Array.isArray(body.detail)) message = "The backend rejected the upload fields.";
        } catch { /* Retain the HTTP message. */ }
        throw new Error(message);
      }
      const result: UploadedPdf = await response.json();
      if (result.saved !== true || !result.document_id || result.source_type !== "pdf" ||
        !result.filename || !Number.isInteger(result.page_count) || result.page_count < 1 ||
        !Array.isArray(result.page_details) || result.page_details.length !== result.page_count ||
        !Array.isArray(result.warnings)) {
        throw new Error("The upload response did not include the saved PDF details. Check that main_v23 is running, and check whether the document was saved before uploading again.");
      }
      if (!controller.signal.aborted) setUploaded(result);
    } catch (caught) {
      if (!controller.signal.aborted) setError(caught instanceof TypeError
        ? "The upload response could not be received. The PDF may already be saved; check the backend before uploading it again."
        : caught instanceof Error ? caught.message : "Unable to upload PDF.");
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null;
        if (!controller.signal.aborted) setUploading(false);
      }
    }
  }

  return (
    <section aria-labelledby="pdf-upload-heading" style={{ marginBottom: "24px", padding: "20px", border: "1px solid #e0e6ed", borderRadius: "12px", background: "#ffffff" }}>
      <h2 id="pdf-upload-heading" style={{ fontSize: "20px", fontWeight: 700 }}>Upload a requirements PDF</h2>
      <p style={{ margin: "10px 0 16px", color: "#596779", fontSize: "13px", lineHeight: 1.6 }}>
        Choose a text-based PDF, up to 10 MB and 100 pages. Scanned images need OCR and are not supported here.
        This step saves the source and page details. Requirement extraction remains a separate step.
      </p>
      <form onSubmit={(event) => void uploadPdf(event)}>
        <label style={{ display: "block", fontSize: "14px", fontWeight: 600 }}>
          PDF file
          <input type="file" accept=".pdf,application/pdf" required disabled={uploading || uploaded !== null}
            onChange={(event) => { setFile(event.target.files?.[0] ?? null); setError(null); }}
            style={{ display: "block", marginTop: "10px", width: "100%", fontSize: "14px" }} />
        </label>
        <button type="submit" disabled={!file || uploading || uploaded !== null}
          style={{ ...buttonStyle, marginTop: "16px", opacity: !file || uploading || uploaded ? 0.6 : 1 }}>
          {uploading ? "Uploading and processing..." : uploaded ? "PDF saved" : "Upload PDF"}
        </button>
      </form>
      {uploading && <p role="status" style={{ marginTop: "12px", fontSize: "13px" }}>Saving the PDF and preparing PDF search. Please wait.</p>}
      {error && <p role="alert" style={{ marginTop: "14px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{error}</p>}
      {uploaded && (
        <div style={{ marginTop: "18px", padding: "18px", background: "#f3f6fa", borderRadius: "10px" }}>
          <p role="status" style={{ color: "#17623b", fontWeight: 600 }}>PDF source saved.</p>
          <p style={{ marginTop: "10px", fontSize: "14px", overflowWrap: "anywhere" }}><strong>Filename:</strong> {uploaded.filename}</p>
          <p style={{ marginTop: "8px", fontSize: "13px", overflowWrap: "anywhere" }}><strong>Document ID:</strong> {uploaded.document_id}</p>
          <p style={{ marginTop: "8px", fontSize: "13px" }}><strong>Pages:</strong> {uploaded.page_count}</p>
          <p style={{ marginTop: "8px", fontSize: "13px" }}><strong>Original PDF:</strong> {uploaded.original_file_saved ? "Saved" : "Not confirmed"}</p>
          <p style={{ marginTop: "8px", fontSize: "13px" }}><strong>PDF search indexing:</strong> {uploaded.pdf_search_indexed ? "Completed" : uploaded.pdf_search_index_status === "unconfirmed" ? "Not confirmed" : "Not completed"}</p>
          <p style={{ marginTop: "12px", fontSize: "13px", lineHeight: 1.6 }}>Preview the requirements below using this document automatically. Uploading this PDF again creates another document. Your currently loaded requirements remain below.</p>
          {uploaded.warnings.map((warning, index) => <p key={index} role="status" style={{ marginTop: "12px", padding: "12px", background: "#fff3d6", color: "#765300", borderRadius: "8px", lineHeight: 1.6 }}>{warning}</p>)}
          <RequirementsPreview key={uploaded.document_id} documentId={uploaded.document_id} />
          <h3 style={{ marginTop: "18px", fontSize: "16px", fontWeight: 700 }}>Extracted page text</h3>
          {uploaded.page_details.map((page) => (
            <details key={page.page} style={{ marginTop: "12px", padding: "12px", border: "1px solid #e0e6ed", borderRadius: "8px", background: "#ffffff" }}>
              <summary style={{ cursor: "pointer", fontWeight: 600, fontSize: "14px" }}>Page {page.page}{page.has_text ? "" : " - no text extracted"}</summary>
              <p style={{ marginTop: "10px", fontSize: "13px", lineHeight: 1.7, whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{page.has_text ? page.text : "No readable text was extracted from this page."}</p>
            </details>
          ))}
        </div>
      )}
    </section>
  );
}

function RequirementsInputForm() {
  const [title, setTitle] = useState("");
  const [text, setText] = useState("");
  const [savedDocument, setSavedDocument] = useState<RequirementsDocument | null>(null);
  const [saving, setSaving] = useState(false);
  const [reading, setReading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [readMessage, setReadMessage] = useState<string | null>(null);
  const controllerRef = useRef<AbortController | null>(null);
  useEffect(() => () => controllerRef.current?.abort(), []);

  async function saveDocument(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (controllerRef.current || savedDocument) return;
    setError(null);
    if (!title.trim() || !text.trim() || title.length > 200 || text.length > 50000) {
      setError("Enter a title (up to 200 characters) and requirements text (up to 50,000 characters).");
      return;
    }
    const controller = new AbortController();
    controllerRef.current = controller;
    setSaving(true);
    try {
      const response = await fetch(`${API_BASE}/requirements/input`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        // Preserve the original text, including blank lines, for source-line references.
        body: JSON.stringify({ title, text }),
        signal: controller.signal,
      });
      if (!response.ok) {
        let message = `Unable to save document (HTTP ${response.status}).`;
        try {
          const data = await response.json();
          if (typeof data.detail === "string") message = data.detail;
          else if (Array.isArray(data.detail)) message = "The title or text failed backend validation.";
        } catch { /* Retain the HTTP message. */ }
        throw new Error(message);
      }
      const result: RequirementsDocument & { saved: boolean } = await response.json();
      if (!result.document_id || result.saved !== true || result.title !== title || result.text !== text) {
        throw new Error("Unexpected save response. Check the backend before submitting the document again.");
      }
      if (!controller.signal.aborted) setSavedDocument(result);
    } catch (caught) {
      if (!controller.signal.aborted) setError(caught instanceof TypeError
        ? "The save response could not be received. The document may have been saved; check the backend before submitting it again."
        : caught instanceof Error ? caught.message : "Unable to save document.");
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null;
        if (!controller.signal.aborted) setSaving(false);
      }
    }
  }

  async function readSavedSource() {
    if (!savedDocument || controllerRef.current) return;
    const expected = savedDocument;
    const controller = new AbortController();
    controllerRef.current = controller;
    setReading(true);
    setError(null);
    setReadMessage(null);
    try {
      const response = await fetch(`${API_BASE}/requirements/documents/${encodeURIComponent(expected.document_id)}`, {
        signal: controller.signal, cache: "no-store",
      });
      if (!response.ok) throw new Error(`Unable to reload saved source (HTTP ${response.status}).`);
      const result: RequirementsDocument = await response.json();
      if (result.document_id !== expected.document_id || typeof result.title !== "string" || typeof result.text !== "string") {
        throw new Error("The backend returned an unexpected document response.");
      }
      if (!controller.signal.aborted) {
        setSavedDocument(result);
        setReadMessage("Saved source reloaded from the backend.");
      }
    } catch (caught) {
      if (!controller.signal.aborted) setError(caught instanceof Error ? caught.message : "Unable to reload saved source.");
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null;
        if (!controller.signal.aborted) setReading(false);
      }
    }
  }

  return (
    <section aria-labelledby="requirements-input-heading" style={{ marginBottom: "24px", padding: "20px", border: "1px solid #e0e6ed", borderRadius: "12px", background: "#ffffff" }}>
      <h2 id="requirements-input-heading" style={{ fontSize: "20px", fontWeight: 700 }}>Enter requirements manually</h2>
      <p style={{ margin: "10px 0 16px", color: "#596779", fontSize: "13px", lineHeight: 1.6 }}>
        Enter a title, then type or paste the requirements. This creates a separate source document;
        it does not add requirements to an uploaded PDF. Your currently loaded document stays visible below.
      </p>
      <form onSubmit={(event) => void saveDocument(event)}>
        <fieldset disabled={saving || savedDocument !== null} style={{ border: 0, margin: 0, padding: 0 }}>
          <label style={{ display: "block", fontSize: "14px", fontWeight: 600 }}>
            Document title
            <input value={title} onChange={(event) => setTitle(event.target.value)} required maxLength={200}
              style={{ display: "block", width: "100%", boxSizing: "border-box", marginTop: "8px", padding: "11px 12px", border: "1px solid #bac5d2", borderRadius: "8px", background: "#ffffff", color: "#1c293b" }} />
          </label>
          <label style={{ display: "block", marginTop: "16px", fontSize: "14px", fontWeight: 600 }}>
            Requirements text
            <textarea value={text} onChange={(event) => setText(event.target.value)} required maxLength={50000} rows={6}
              style={{ display: "block", width: "100%", boxSizing: "border-box", marginTop: "8px", padding: "11px 12px", border: "1px solid #bac5d2", borderRadius: "8px", background: "#ffffff", color: "#1c293b", fontFamily: "inherit", fontSize: "14px", lineHeight: 1.6, resize: "vertical" }} />
          </label>
          <button type="submit" style={{ ...buttonStyle, marginTop: "16px", opacity: saving || savedDocument ? 0.6 : 1 }}>
            {saving ? "Saving document..." : savedDocument ? "Document saved" : "Save document"}
          </button>
        </fieldset>
      </form>
      {error && <p role="alert" style={{ marginTop: "14px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{error}</p>}
      {savedDocument && (
        <div style={{ marginTop: "18px", padding: "18px", borderRadius: "10px", background: "#f3f6fa" }}>
          <p role="status" style={{ color: "#17623b", fontWeight: 600 }}>Source document saved: {savedDocument.title}</p>
          <p style={{ marginTop: "10px", fontSize: "13px", overflowWrap: "anywhere" }}><strong>Document ID:</strong> {savedDocument.document_id}</p>
          <p style={{ marginTop: "8px", fontSize: "13px" }}>{savedDocument.characters} characters · Created {new Date(savedDocument.created_at).toLocaleString()}</p>
          <p style={{ marginTop: "12px", fontSize: "13px", lineHeight: 1.6 }}>Keep this ID so you can load the document later. No requirement IDs or test cases have been created by this form.</p>
          <button type="button" disabled={reading} onClick={() => void readSavedSource()}
            style={{ ...buttonStyle, marginTop: "14px", background: "#ffffff", color: "#24634f", opacity: reading ? 0.6 : 1 }}>{reading ? "Reloading source..." : "Reload saved source"}</button>
          {readMessage && <p role="status" style={{ marginTop: "12px", color: "#17623b", fontSize: "13px" }}>{readMessage}</p>}
          <details style={{ marginTop: "16px" }}><summary style={{ cursor: "pointer", fontWeight: 600 }}>Saved source text</summary>
            <p style={{ marginTop: "12px", whiteSpace: "pre-wrap", overflowWrap: "anywhere", lineHeight: 1.7 }}>{savedDocument.text}</p>
          </details>
        </div>
      )}
    </section>
  );
}

type TraceabilityResponse = {
  document_id: string;
  title: string;
  requirement_count: number;
  linked_test_count: number;
  requirements: {
    document_id: string;
    requirement_id: string;
    text: string;
    source_line: number;
    source_text: string;
    test_case_count: number;
    test_cases: {
      test_case_id: string;
      title: string;
      status: SavedTestCase["status"];
      created_at: string;
      review: SavedTestCase["review"];
    }[];
  }[];
};

function TraceabilityView({ coverage, onViewTests }: { coverage: CoverageResponse; onViewTests: (requirementId: string) => void }) {
  const [data, setData] = useState<TraceabilityResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [refresh, setRefresh] = useState(0);

  useEffect(() => {
    const controller = new AbortController();
    setLoading(true);
    setData(null);
    setError(null);
    async function load() {
      try {
        const response = await fetch(`${API_BASE}/requirements/documents/${encodeURIComponent(coverage.document_id)}/traceability`, {
          signal: controller.signal, cache: "no-store",
        });
        if (!response.ok) {
          let message = `Unable to load traceability (HTTP ${response.status}).`;
          try {
            const body = await response.json();
            if (typeof body.detail === "string") message = body.detail;
          } catch { /* Retain the HTTP message. */ }
          throw new Error(message);
        }
        const result: TraceabilityResponse = await response.json();
        if (result.document_id !== coverage.document_id || !Array.isArray(result.requirements) ||
          result.requirements.some((requirement) => requirement.document_id !== coverage.document_id || !Array.isArray(requirement.test_cases))) {
          throw new Error("The backend returned an unexpected traceability response.");
        }
        if (!controller.signal.aborted) setData(result);
      } catch (caught) {
        if (!controller.signal.aborted) setError(caught instanceof TypeError
          ? "Cannot reach the backend to load traceability."
          : caught instanceof Error ? caught.message : "Unable to load traceability.");
      } finally {
        if (!controller.signal.aborted) setLoading(false);
      }
    }
    void load();
    return () => controller.abort();
  }, [coverage, refresh]);

  return (
    <section aria-labelledby="traceability-heading" style={{ marginTop: "26px" }}>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: "12px", flexWrap: "wrap" }}>
        <h3 id="traceability-heading" style={{ fontSize: "20px", fontWeight: 700 }}>Requirement-to-test traceability</h3>
        <button type="button" disabled={loading} onClick={() => setRefresh((value) => value + 1)}
          style={{ ...buttonStyle, background: "#ffffff", color: "#24634f", opacity: loading ? 0.6 : 1 }}>Refresh traceability</button>
      </div>
      <p style={{ margin: "12px 0", color: "#596779", fontSize: "13px", lineHeight: 1.6 }}>
        Each row links a saved requirement to a saved test and its review. Requirements without tests remain visible.
        Source lines refer to the stored text document. Review status concerns test design, not execution.
      </p>
      {loading && <p role="status">Loading traceability...</p>}
      {error && <p role="alert" style={{ padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{error}</p>}
      {data && !loading && (
        <>
          <p style={{ margin: "14px 0", fontSize: "14px" }}><strong>{data.title}</strong> · {data.requirement_count} requirements · {data.linked_test_count} linked tests</p>
          {data.requirements.length === 0 ? <p>No saved requirements to display.</p> : (
            <div style={{ overflowX: "auto", border: "1px solid #e0e6ed", borderRadius: "10px", background: "#ffffff" }}>
              <table style={{ width: "100%", minWidth: "1050px", borderCollapse: "collapse", fontSize: "13px" }}>
                <thead style={{ background: "#edf2f7" }}>
                  <tr>{["Requirement", "Source", "Linked test", "Review status", "Review note", "Details"].map((label) => (
                    <th key={label} scope="col" style={{ ...cellStyle, fontWeight: 600 }}>{label}</th>
                  ))}</tr>
                </thead>
                <tbody>
                  {data.requirements.flatMap((requirement) => {
                    const tests = requirement.test_cases.length ? requirement.test_cases : [null];
                    return tests.map((test) => {
                      const colors = test?.status === "approved" ? statusColors.covered
                        : test?.status === "rejected" ? statusColors.rejected_only
                        : test ? statusColors.drafts_pending_review : statusColors.no_tests;
                      return (
                        <tr key={`${requirement.requirement_id}:${test?.test_case_id ?? "none"}`}>
                          <th scope="row" style={{ ...cellStyle, minWidth: "210px", fontWeight: 400 }}>
                            <strong>{requirement.requirement_id}</strong>
                            <p style={{ marginTop: "8px", lineHeight: 1.6 }}>{requirement.text}</p>
                          </th>
                          <td style={{ ...cellStyle, minWidth: "200px" }}>
                            <strong>Line {requirement.source_line}</strong>
                            <p style={{ marginTop: "8px", lineHeight: 1.6, whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{requirement.source_text}</p>
                          </td>
                          <td style={{ ...cellStyle, minWidth: "210px" }}>
                            {test ? <><strong>{test.title}</strong><p style={{ marginTop: "8px", fontSize: "12px", color: "#596779", overflowWrap: "anywhere" }}>{test.test_case_id}</p></> : "No linked test"}
                          </td>
                          <td style={cellStyle}><span style={{ ...colors, display: "inline-block", padding: "6px 9px", borderRadius: "6px", whiteSpace: "nowrap" }}>
                            {test?.status === "approved" ? "Approved" : test?.status === "rejected" ? "Rejected" : test ? "Draft" : "No tests"}
                          </span></td>
                          <td style={{ ...cellStyle, minWidth: "220px", lineHeight: 1.6 }}>
                            {test?.review ? <><p style={{ whiteSpace: "pre-wrap", overflowWrap: "anywhere" }}>{test.review.note}</p><p style={{ marginTop: "8px", fontSize: "12px", color: "#596779" }}>{new Date(test.review.reviewed_at).toLocaleString()}</p></> : test ? "Awaiting review" : "—"}
                          </td>
                          <td style={cellStyle}>{test ? <button type="button" onClick={() => onViewTests(requirement.requirement_id)}
                            style={{ ...buttonStyle, background: "#ffffff", color: "#24634f", padding: "7px 10px", whiteSpace: "nowrap", fontSize: "12px" }}>View tests</button> : "—"}</td>
                        </tr>
                      );
                    });
                  })}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}
    </section>
  );
}

type EditableFields = {
  title: string;
  preconditions: string;
  test_data: string;
  steps: string;
  expected_result: string;
  assumptions: string;
};

function editableFields(test: TestCaseContent): EditableFields {
  return {
    title: test.title,
    preconditions: test.preconditions.join("\n"),
    test_data: test.test_data.join("\n"),
    steps: test.steps.join("\n"),
    expected_result: test.expected_result,
    assumptions: test.assumptions.join("\n"),
  };
}

function DraftEditor({ record, onUpdated, onReviewed }: { record: SavedTestCase; onUpdated: (record: SavedTestCase) => void; onReviewed?: (record: SavedTestCase) => void }) {
  const [reviewNote, setReviewNote] = useState("");
  const [reviewing, setReviewing] = useState<"approved" | "rejected" | null>(null);
  const [editing, setEditing] = useState(false);
  const [fields, setFields] = useState<EditableFields>(() => editableFields(record.test_case));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const controllerRef = useRef<AbortController | null>(null);
  useEffect(() => () => controllerRef.current?.abort(), []);

  const labels: { key: keyof EditableFields; label: string; rows: number }[] = [
    { key: "title", label: "Title", rows: 1 },
    { key: "preconditions", label: "Preconditions — one item per line", rows: 3 },
    { key: "test_data", label: "Test data — one item per line", rows: 3 },
    { key: "steps", label: "Steps — one step per line", rows: 4 },
    { key: "expected_result", label: "Expected result", rows: 3 },
    { key: "assumptions", label: "Assumptions — one item per line (optional)", rows: 3 },
  ];

  async function saveChanges(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (controllerRef.current) return;
    setError(null);
    setMessage(null);
    const lines = (value: string) => value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
    // The PUT schema accepts content only; the backend preserves both source IDs.
    const body = {
      title: fields.title.trim(),
      preconditions: lines(fields.preconditions),
      test_data: lines(fields.test_data),
      steps: lines(fields.steps),
      expected_result: fields.expected_result.trim(),
      assumptions: lines(fields.assumptions),
    };
    if (!body.title || body.title.length > 200 || !body.expected_result ||
      !body.preconditions.length || !body.test_data.length || !body.steps.length) {
      setError("Enter a title (up to 200 characters), expected result, and at least one item each for preconditions, test data, and steps.");
      return;
    }
    const controller = new AbortController();
    controllerRef.current = controller;
    setSaving(true);
    try {
      const response = await fetch(`${API_BASE}/test-cases/${encodeURIComponent(record.test_case_id)}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
        signal: controller.signal,
      });
      if (!response.ok) {
        let detail = `Unable to update draft (HTTP ${response.status}).`;
        try {
          const data = await response.json();
          if (typeof data.detail === "string") detail = data.detail;
          else if (Array.isArray(data.detail)) detail = "The backend rejected a field. Check the values and try again.";
        } catch { /* Retain the HTTP error. */ }
        throw new Error(detail);
      }
      const updated: SavedTestCase & { updated: boolean } = await response.json();
      if (updated.test_case_id !== record.test_case_id || updated.document_id !== record.document_id ||
        updated.requirement_id !== record.requirement_id || updated.status !== "draft" ||
        updated.saved !== true || updated.updated !== true ||
        updated.test_case?.document_id !== record.document_id ||
        updated.test_case?.requirement_id !== record.requirement_id ||
        updated.requirement_snapshot?.document_id !== record.document_id ||
        updated.requirement_snapshot?.requirement_id !== record.requirement_id) {
        throw new Error("Unexpected update response. Reload the saved test to check its contents.");
      }
      if (controller.signal.aborted) return;
      onUpdated({ ...updated, review: null });
      setEditing(false);
      setMessage("Changes saved. This test is still a draft awaiting review.");
    } catch (caught) {
      if (!controller.signal.aborted) setError(caught instanceof TypeError
        ? "The update response could not be received. Reload the saved test to check whether your changes were stored."
        : caught instanceof Error ? caught.message : "Unable to update draft.");
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null;
        if (!controller.signal.aborted) setSaving(false);
      }
    }
  }

  async function submitReview(decision: "approved" | "rejected") {
    if (!onReviewed || controllerRef.current) return;
    const note = reviewNote.trim();
    setError(null);
    setMessage(null);
    if (!note || note.length > 4000) {
      setError("Enter a review note of 1 to 4,000 characters before approving or rejecting.");
      return;
    }
    const controller = new AbortController();
    controllerRef.current = controller;
    setReviewing(decision);
    try {
      const response = await fetch(`${API_BASE}/test-cases/${encodeURIComponent(record.test_case_id)}/review`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ decision, note }),
        signal: controller.signal,
      });
      if (!response.ok) {
        let detail = `Unable to save review (HTTP ${response.status}).`;
        try {
          const data = await response.json();
          if (typeof data.detail === "string") detail = data.detail;
          else if (Array.isArray(data.detail)) detail = "The review note or decision failed validation.";
        } catch { /* Retain the HTTP error. */ }
        throw new Error(detail);
      }
      const reviewed: SavedTestCase & { review_saved: boolean } = await response.json();
      if (reviewed.test_case_id !== record.test_case_id || reviewed.document_id !== record.document_id ||
        reviewed.requirement_id !== record.requirement_id || reviewed.status !== decision ||
        reviewed.review_saved !== true || reviewed.saved !== true || reviewed.review?.decision !== decision ||
        reviewed.test_case?.document_id !== record.document_id || reviewed.test_case?.requirement_id !== record.requirement_id) {
        throw new Error("Unexpected review response. Use Load / refresh to check the saved review before trying again.");
      }
      if (!controller.signal.aborted) onReviewed(reviewed);
    } catch (caught) {
      if (!controller.signal.aborted) setError(caught instanceof TypeError
        ? "The review response could not be received. Use Load / refresh to check whether the review was saved before trying again."
        : caught instanceof Error ? caught.message : "Unable to save review.");
    } finally {
      if (controllerRef.current === controller) {
        controllerRef.current = null;
        if (!controller.signal.aborted) setReviewing(null);
      }
    }
  }

  return (
    <div style={{ marginTop: "22px", borderTop: "1px solid #e0e6ed", paddingTop: "18px" }}>
      {message && <p role="status" style={{ color: "#17623b", marginBottom: "12px" }}>{message}</p>}
      {!editing ? (
        <>
        <button type="button" disabled={reviewing !== null} style={{ ...buttonStyle, opacity: reviewing ? 0.6 : 1 }} onClick={() => {
          setFields(editableFields(record.test_case));
          setError(null);
          setMessage(null);
          setEditing(true);
        }}>Edit draft</button>
        {onReviewed && (
          <div style={{ marginTop: "22px" }}>
            <h5 style={{ fontSize: "17px", fontWeight: 700 }}>Review this draft</h5>
            <p style={{ margin: "10px 0", fontSize: "13px", color: "#596779", lineHeight: 1.6 }}>
              Check the test against its source requirement. Approval records a test-design decision;
              it does not mean the test was executed or passed. A reviewed test cannot be edited or reviewed again through the current workflow.
            </p>
            <label style={{ display: "block", fontSize: "14px", fontWeight: 600 }}>
              Review note (required)
              <textarea value={reviewNote} maxLength={4000} rows={3} disabled={reviewing !== null}
                onChange={(event) => setReviewNote(event.target.value)}
                style={{ display: "block", width: "100%", boxSizing: "border-box", marginTop: "8px", padding: "10px 12px", border: "1px solid #bac5d2", borderRadius: "8px", background: "#ffffff", color: "#1c293b", fontFamily: "inherit", fontSize: "14px", lineHeight: 1.6, resize: "vertical" }} />
            </label>
            <div style={{ display: "flex", gap: "12px", flexWrap: "wrap", marginTop: "14px" }}>
              <button type="button" disabled={reviewing !== null || !reviewNote.trim()}
                onClick={() => void submitReview("approved")}
                style={{ ...buttonStyle, opacity: reviewing || !reviewNote.trim() ? 0.6 : 1 }}>
                {reviewing === "approved" ? "Approving..." : "Approve"}
              </button>
              <button type="button" disabled={reviewing !== null || !reviewNote.trim()}
                onClick={() => void submitReview("rejected")}
                style={{ ...buttonStyle, background: "#9d2929", borderColor: "#9d2929", opacity: reviewing || !reviewNote.trim() ? 0.6 : 1 }}>
                {reviewing === "rejected" ? "Rejecting..." : "Reject"}
              </button>
            </div>
            {reviewing && <p role="status" style={{ marginTop: "12px" }}>Saving review...</p>}
          </div>
        )}
        {error && <p role="alert" style={{ marginTop: "14px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{error}</p>}
        </>
      ) : (
        <form onSubmit={(event) => void saveChanges(event)}>
          <h5 style={{ fontSize: "17px", fontWeight: 700 }}>Edit saved draft</h5>
          <p style={{ margin: "10px 0 16px", fontSize: "13px", color: "#596779", lineHeight: 1.6 }}>
            Compare your changes with the source requirement above. List fields use one item per line;
            blank lines are omitted. Saving replaces this draft’s content. Cancel discards unsaved edits.
          </p>
          <fieldset disabled={saving} style={{ border: 0, padding: 0, margin: 0 }}>
            {labels.map(({ key, label, rows }) => (
              <label key={key} style={{ display: "block", marginTop: "14px", fontSize: "14px", fontWeight: 600 }}>
                {label}
                <textarea
                  value={fields[key]}
                  rows={rows}
                  required={key !== "assumptions"}
                  maxLength={key === "title" ? 200 : undefined}
                  onChange={(event) => setFields((current) => ({ ...current, [key]: event.target.value }))}
                  style={{ display: "block", width: "100%", boxSizing: "border-box", marginTop: "8px", padding: "10px 12px", border: "1px solid #bac5d2", borderRadius: "8px", background: "#ffffff", color: "#1c293b", fontFamily: "inherit", fontSize: "14px", lineHeight: 1.6, resize: "vertical" }}
                />
              </label>
            ))}
            <div style={{ display: "flex", gap: "12px", marginTop: "18px", flexWrap: "wrap" }}>
              <button type="submit" style={{ ...buttonStyle, opacity: saving ? 0.6 : 1 }}>{saving ? "Saving changes..." : "Save changes"}</button>
              <button type="button" onClick={() => { setEditing(false); setError(null); }} style={{ ...buttonStyle, background: "#ffffff", color: "#24634f" }}>Cancel</button>
            </div>
          </fieldset>
          {error && <p role="alert" style={{ marginTop: "14px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{error}</p>}
        </form>
      )}
    </div>
  );
}

const statusLabels: Record<CoverageStatus, string> = {
  covered: "Approved test available",
  drafts_pending_review: "Drafts awaiting review",
  rejected_only: "Rejected tests only",
  no_tests: "No tests",
};

const statusColors: Record<CoverageStatus, { background: string; color: string }> = {
  covered: { background: "#e7f5ed", color: "#17623b" },
  drafts_pending_review: { background: "#fff3d6", color: "#765300" },
  rejected_only: { background: "#fde9e9", color: "#9d2929" },
  no_tests: { background: "#edf0f4", color: "#465366" },
};

const cellStyle: CSSProperties = {
  padding: "15px 16px",
  borderBottom: "1px solid #e5e9ef",
  textAlign: "left",
  verticalAlign: "top",
};

const buttonStyle: CSSProperties = {
  padding: "11px 18px",
  border: "1px solid #24634f",
  borderRadius: "8px",
  background: "#24634f",
  color: "#ffffff",
  fontWeight: 600,
  cursor: "pointer",
};

export default function Home() {
  const [showTraceability, setShowTraceability] = useState(false);
  const [backendStatus, setBackendStatus] = useState("Checking...");
  const [documentInput, setDocumentInput] = useState(INITIAL_DOCUMENT_ID);
  const [documentId, setDocumentId] = useState(INITIAL_DOCUMENT_ID);
  const [refreshCount, setRefreshCount] = useState(0);
  const [coverage, setCoverage] = useState<CoverageResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedRequirementId, setSelectedRequirementId] = useState<string | null>(null);
  const [savedTests, setSavedTests] = useState<SavedTestCase[]>([]);
  const [testsLoading, setTestsLoading] = useState(false);
  const [testErrors, setTestErrors] = useState<string[]>([]);
  const [generatedDraft, setGeneratedDraft] = useState<GeneratedDraft | null>(null);
  const [generatingRequirementId, setGeneratingRequirementId] = useState<string | null>(null);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const generationController = useRef<AbortController | null>(null);
  const [savingDraft, setSavingDraft] = useState(false);
  const [savedDraftId, setSavedDraftId] = useState<string | null>(null);
  const [savedGeneratedDraft, setSavedGeneratedDraft] = useState<SavedTestCase | null>(null);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [saveWarnings, setSaveWarnings] = useState<string[]>([]);
  const saveController = useRef<AbortController | null>(null);
  const reviewRefreshController = useRef<AbortController | null>(null);
  const [reviewMessage, setReviewMessage] = useState<string | null>(null);
  const [reviewWarning, setReviewWarning] = useState<string | null>(null);
  useEffect(() => () => reviewRefreshController.current?.abort(), []);

  useEffect(() => () => saveController.current?.abort(), []);


  useEffect(() => () => generationController.current?.abort(), []);

  const selectedRequirement = coverage?.requirements.find(
    (requirement) => requirement.requirement_id === selectedRequirementId,
  );


  useEffect(() => {
    const controller = new AbortController();
    setBackendStatus("Checking...");

    async function checkBackend() {
      try {
        const response = await fetch(`${API_BASE}/health`, {
          signal: controller.signal,
          cache: "no-store",
        });
        if (!response.ok) throw new Error("Health check failed.");
        const data = await response.json();
        if (!controller.signal.aborted) {
          setBackendStatus(data.status === "healthy" ? "Connected" : "Unavailable");
        }
      } catch {
        if (!controller.signal.aborted) setBackendStatus("Not connected");
      }
    }

    void checkBackend();
    return () => controller.abort();
  }, [refreshCount]);

  useEffect(() => {
    const controller = new AbortController();
    setLoading(true);
    setError(null);
    setCoverage(null);

    async function loadCoverage() {
      try {
        const response = await fetch(
          `${API_BASE}/requirements/documents/${encodeURIComponent(documentId)}/coverage`,
          { signal: controller.signal, cache: "no-store" },
        );

        if (!response.ok) {
          let message = `Unable to load document (HTTP ${response.status}).`;
          try {
            const body = await response.json();
            if (typeof body.detail === "string") message = body.detail;
          } catch {
            // Retain the HTTP message when the error body is not JSON.
          }
          throw new Error(message);
        }

        const data: CoverageResponse = await response.json();
        if (!Array.isArray(data.requirements)) {
          throw new Error("The backend returned an unexpected coverage response.");
        }
        if (!controller.signal.aborted) setCoverage(data);
      } catch (caught) {
        if (!controller.signal.aborted) {
          setError(
            caught instanceof TypeError
              ? "Cannot reach the backend. Check that FastAPI is running and open the frontend at http://localhost:3000."
              : caught instanceof Error
                ? caught.message
                : "Unable to load coverage.",
          );
        }
      } finally {
        if (!controller.signal.aborted) setLoading(false);
      }
    }

    void loadCoverage();
    return () => controller.abort();
  }, [documentId, refreshCount]);

  useEffect(() => {
    const controller = new AbortController();
    setSavedTests([]);
    setTestErrors([]);
    setTestsLoading(false);
    if (!selectedRequirement || selectedRequirement.test_case_ids.length === 0) {
      return () => controller.abort();
    }
    const requirement = selectedRequirement;
    setTestsLoading(true);

    async function loadSavedTests() {
      const results = await Promise.allSettled(
        requirement.test_case_ids.map(async (id) => {
          const response = await fetch(`${API_BASE}/test-cases/${encodeURIComponent(id)}`, {
            signal: controller.signal,
            cache: "no-store",
          });
          if (!response.ok) {
            let message = `Unable to load test ${id} (HTTP ${response.status}).`;
            try {
              const body = await response.json();
              if (typeof body.detail === "string") message = `Test ${id}: ${body.detail}`;
            } catch { /* Keep the HTTP error when the response is not JSON. */ }
            throw new Error(message);
          }
          const record: SavedTestCase = await response.json();
          if (record.document_id !== requirement.document_id || record.requirement_id !== requirement.requirement_id || record.test_case_id !== id) {
            throw new Error(`Test ${id} has an unexpected requirement link.`);
          }
          return record;
        }),
      );
      if (controller.signal.aborted) return;
      const loaded: SavedTestCase[] = [];
      const errors: string[] = [];
      for (const result of results) {
        if (result.status === "fulfilled") loaded.push(result.value);
        else errors.push(result.reason instanceof Error ? result.reason.message : "Unable to load a saved test.");
      }
      setSavedTests(loaded);
      setTestErrors(errors);
      setTestsLoading(false);
    }

    void loadSavedTests();
    return () => controller.abort();
  }, [selectedRequirement]);

  async function handleGenerate(requirement: RequirementCoverage) {
    // A ref blocks duplicate submissions before React updates the button state.
    if (generationController.current || saveController.current) return;
    setSavedDraftId(null);
    setSavedGeneratedDraft(null);
    setSaveError(null);
    setSaveWarnings([]);
    const controller = new AbortController();
    generationController.current = controller;
    setGeneratingRequirementId(requirement.requirement_id);
    setGeneratedDraft(null);
    setGenerationError(null);

    try {
      const response = await fetch(
        `${API_BASE}/requirements/documents/${encodeURIComponent(requirement.document_id)}/requirements/${encodeURIComponent(requirement.requirement_id)}/generate`,
        { method: "POST", signal: controller.signal },
      );
      if (!response.ok) {
        let message = `Generation failed (HTTP ${response.status}).`;
        try {
          const body = await response.json();
          if (typeof body.detail === "string") message = body.detail;
          else if (body.detail && typeof body.detail.message === "string") message = body.detail.message;
        } catch { /* Retain HTTP information for non-JSON error responses. */ }
        throw new Error(message);
      }
      const draft: GeneratedDraft = await response.json();
      if (
        draft.document_id !== requirement.document_id ||
        draft.requirement_id !== requirement.requirement_id ||
        draft.test_case?.document_id !== requirement.document_id ||
        draft.test_case?.requirement_id !== requirement.requirement_id ||
        draft.target_requirement?.requirement_id !== requirement.requirement_id ||
        draft.target_requirement?.document_id !== requirement.document_id ||
        draft.saved !== false
      ) {
        throw new Error("The generated draft has an unexpected requirement link or save status.");
      }
      if (!controller.signal.aborted) setGeneratedDraft(draft);
    } catch (caught) {
      if (!controller.signal.aborted) {
        setGenerationError(
          caught instanceof TypeError
            ? "Cannot reach the backend. Check that FastAPI is running."
            : caught instanceof Error ? caught.message : "Unable to generate a draft.",
        );
      }
    } finally {
      if (generationController.current === controller) {
        generationController.current = null;
        if (!controller.signal.aborted) setGeneratingRequirementId(null);
      }
    }
  }

  async function handleSaveDraft() {
    if (!generatedDraft || savedDraftId || saveController.current || generationController.current) return;
    const draft = generatedDraft;
    const controller = new AbortController();
    saveController.current = controller;
    setSavingDraft(true);
    setSaveError(null);
    setSaveWarnings([]);

    async function readUpdatedData<T>(url: string): Promise<T> {
      const response = await fetch(url, { signal: controller.signal, cache: "no-store" });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return response.json();
    }

    try {
      const response = await fetch(
        `${API_BASE}/requirements/documents/${encodeURIComponent(draft.document_id)}/requirements/${encodeURIComponent(draft.requirement_id)}/test-cases`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(draft.test_case),
          signal: controller.signal,
        },
      );
      if (!response.ok) {
        let message = `Unable to save draft (HTTP ${response.status}).`;
        try {
          const body = await response.json();
          if (typeof body.detail === "string") message = body.detail;
          else if (Array.isArray(body.detail)) message = "The draft failed field validation. Review it before saving.";
        } catch { /* Keep the HTTP message for non-JSON responses. */ }
        throw new Error(message);
      }
      const saved: { test_case_id: string; document_id: string; requirement_id: string; saved: boolean; status: string } = await response.json();
      if (
        !saved.test_case_id || saved.saved !== true || saved.status !== "draft" ||
        saved.document_id !== draft.document_id || saved.requirement_id !== draft.requirement_id
      ) {
        throw new Error("Unexpected save response. Check View tests before trying to save again.");
      }
      if (controller.signal.aborted) return;
      // Keep the ID even if the following read requests fail; never repeat the POST.
      setSavedDraftId(saved.test_case_id);

      const results = await Promise.allSettled([
        readUpdatedData<SavedTestCase>(`${API_BASE}/test-cases/${encodeURIComponent(saved.test_case_id)}`),
        readUpdatedData<CoverageResponse>(`${API_BASE}/requirements/documents/${encodeURIComponent(draft.document_id)}/coverage`),
      ]);
      if (controller.signal.aborted) return;
      const warnings: string[] = [];
      const details = results[0];
      if (
        details.status === "fulfilled" && details.value.test_case_id === saved.test_case_id &&
        details.value.document_id === draft.document_id && details.value.requirement_id === draft.requirement_id
      ) {
        setSavedGeneratedDraft(details.value);
      } else {
        warnings.push("The draft was saved, but its details could not be reloaded. Use Load / refresh and View tests to read it.");
      }
      const updatedCoverage = results[1];
      if (
        updatedCoverage.status === "fulfilled" && updatedCoverage.value.document_id === draft.document_id &&
        Array.isArray(updatedCoverage.value.requirements)
      ) {
        setCoverage(updatedCoverage.value);
      } else {
        warnings.push("The draft was saved, but the table could not be refreshed. Use Load / refresh to update the counts.");
      }
      setSaveWarnings(warnings);
    } catch (caught) {
      if (!controller.signal.aborted) {
        setSaveError(
          caught instanceof TypeError
            ? "The save response could not be received. Use Load / refresh and View tests to check whether it was saved before trying again."
            : caught instanceof Error ? caught.message : "Unable to save draft.",
        );
      }
    } finally {
      if (saveController.current === controller) {
        saveController.current = null;
        if (!controller.signal.aborted) setSavingDraft(false);
      }
    }
  }

  function handleDraftUpdated(updated: SavedTestCase) {
    setSavedTests((records) => records.map((record) => record.test_case_id === updated.test_case_id ? updated : record));
    setSavedGeneratedDraft((record) => record?.test_case_id === updated.test_case_id ? updated : record);
    setCoverage((current) => current ? { ...current } : current);
  }

  function handleReviewed(reviewed: SavedTestCase) {
    handleDraftUpdated(reviewed);
    setReviewMessage(`Review saved: ${reviewed.requirement_id} test is ${reviewed.status}.`);
    setReviewWarning(null);
    reviewRefreshController.current?.abort();
    const controller = new AbortController();
    reviewRefreshController.current = controller;
    async function refreshCoverage() {
      try {
        const response = await fetch(`${API_BASE}/requirements/documents/${encodeURIComponent(reviewed.document_id)}/coverage`, {
          signal: controller.signal, cache: "no-store",
        });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data: CoverageResponse = await response.json();
        if (data.document_id !== reviewed.document_id || !Array.isArray(data.requirements)) throw new Error("Unexpected coverage response.");
        if (!controller.signal.aborted) setCoverage(data);
      } catch {
        if (!controller.signal.aborted) setReviewWarning("The review was saved, but coverage could not be refreshed. Use Load / refresh to update the table and counts.");
      } finally {
        if (reviewRefreshController.current === controller) reviewRefreshController.current = null;
      }
    }
    void refreshCoverage();
  }

  function handleLoad(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const nextId = documentInput.trim();
    if (!nextId || generationController.current || saveController.current) return;
    reviewRefreshController.current?.abort();
    reviewRefreshController.current = null;
    setReviewMessage(null);
    setReviewWarning(null);
    setSavedDraftId(null);
    setSavedGeneratedDraft(null);
    setSaveError(null);
    setSaveWarnings([]);
    setGeneratedDraft(null);
    setGenerationError(null);
    setSelectedRequirementId(null);
    setDocumentId(nextId);
    setRefreshCount((count) => count + 1);
  }

  return (
    <main
      style={{
        minHeight: "100vh",
        padding: "32px 20px",
        background: "#f5f7fa",
        color: "#1c293b",
        fontFamily: "Arial, sans-serif",
      }}
    >
      <div style={{ maxWidth: "1150px", margin: "0 auto" }}>
        <header style={{ marginBottom: "26px" }}>
          <p style={{ color: "#24634f", fontSize: "13px", fontWeight: 700, marginBottom: "8px" }}>
            COMP902 PROJECT PROTOTYPE
          </p>
          <h1 style={{ fontSize: "30px", fontWeight: 700, marginBottom: "10px" }}>
            AI-Assisted Test Case Generation
          </h1>
          <p style={{ color: "#596779", lineHeight: 1.6 }}>
            Requirements and approved test-design coverage
          </p>
          <p style={{ marginTop: "12px", fontSize: "14px" }} aria-live="polite">
            <strong>Backend status:</strong> {backendStatus}
          </p>
        </header>

        <RequirementsEntry />

        <form
          onSubmit={handleLoad}
          style={{ padding: "20px", border: "1px solid #e0e6ed", borderRadius: "12px", background: "#ffffff" }}
        >
          <label htmlFor="document-id" style={{ display: "block", fontWeight: 600, marginBottom: "10px" }}>
            Saved document ID
          </label>
          <div style={{ display: "flex", gap: "12px", flexWrap: "wrap" }}>
            <input
              id="document-id"
              value={documentInput}
              onChange={(event) => setDocumentInput(event.target.value)}
              required
              spellCheck={false}
              autoComplete="off"
              style={{ flex: "1 1 300px", minWidth: 0, border: "1px solid #bac5d2", borderRadius: "8px", padding: "11px 12px", background: "#ffffff", color: "#1c293b" }}
            />
            <button
              type="submit"
              disabled={loading || generatingRequirementId !== null || savingDraft || !documentInput.trim()}
              style={{ ...buttonStyle, opacity: loading || generatingRequirementId !== null || savingDraft || !documentInput.trim() ? 0.6 : 1 }}
            >
              {loading ? "Loading..." : "Load / refresh"}
            </button>
          </div>
        </form>

        {loading && <p role="status" style={{ marginTop: "24px" }}>Loading requirements and coverage...</p>}
        {error && (
          <p role="alert" style={{ marginTop: "24px", padding: "16px", borderRadius: "8px", background: "#fde9e9", color: "#9d2929" }}>
            {error}
          </p>
        )}

        {coverage && !loading && (
          <section style={{ marginTop: "28px" }} aria-labelledby="document-title">
            <h2 id="document-title" style={{ fontSize: "22px", fontWeight: 700, marginBottom: "16px" }}>
              {coverage.title}
            </h2>

            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "14px" }}>
              {[
                { label: "Saved requirements", value: coverage.requirement_count },
                { label: "With approved tests", value: coverage.covered_requirement_count },
                { label: "Without approved tests", value: coverage.uncovered_requirement_count },
                {
                  label: "Approved test-design coverage",
                  value: coverage.coverage_percentage === null ? "N/A" : `${coverage.coverage_percentage.toFixed(2)}%`,
                },
              ].map((card) => (
                <div key={card.label} style={{ padding: "20px", border: "1px solid #e0e6ed", borderRadius: "10px", background: "#ffffff" }}>
                  <p style={{ fontSize: "13px", color: "#596779", marginBottom: "10px", lineHeight: 1.5 }}>{card.label}</p>
                  <p style={{ fontSize: "28px", fontWeight: 700 }}>{card.value}</p>
                </div>
              ))}
            </div>

            <p style={{ margin: "16px 0 24px", fontSize: "13px", color: "#596779", lineHeight: 1.6 }}>
              A requirement counts as covered when it has at least one approved test.
              This does not indicate that tests have been executed or that all scenarios are covered.
            </p>

            <h3 style={{ fontSize: "18px", fontWeight: 700, marginBottom: "12px" }}>Saved requirements</h3>
            {coverage.requirements.length === 0 ? (
              <div>
                <p style={{ padding: "20px", background: "#ffffff", borderRadius: "10px" }}>
                  This document has no saved extracted requirements yet. Preview its requirements below.
                </p>
                <RequirementsPreview key={coverage.document_id} documentId={coverage.document_id} />
              </div>
            ) : (
              <div style={{ overflowX: "auto", border: "1px solid #e0e6ed", borderRadius: "10px", background: "#ffffff" }}>
                <table style={{ width: "100%", minWidth: "850px", borderCollapse: "collapse", fontSize: "14px" }}>
                  <thead style={{ background: "#edf2f7" }}>
                    <tr>
                      {['ID', 'Requirement', 'Source line', 'Coverage status', 'Approved / Draft / Rejected', 'Actions'].map((heading) => (
                        <th key={heading} scope="col" style={{ ...cellStyle, fontWeight: 600 }}>{heading}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {coverage.requirements.map((requirement) => (
                      <tr key={`${requirement.document_id}:${requirement.requirement_id}`} style={{ background: selectedRequirementId === requirement.requirement_id ? "#f0f7f4" : undefined }}>
                        <th scope="row" style={{ ...cellStyle, whiteSpace: "nowrap", fontWeight: 600 }}>{requirement.requirement_id}</th>
                        <td style={{ ...cellStyle, minWidth: "260px", lineHeight: 1.6 }}>{requirement.text}</td>
                        <td style={cellStyle}>{requirement.source_line}</td>
                        <td style={cellStyle}>
                          <span style={{ ...statusColors[requirement.coverage_status], display: "inline-block", padding: "6px 9px", borderRadius: "6px", fontSize: "12px", whiteSpace: "nowrap" }}>
                            {statusLabels[requirement.coverage_status]}
                          </span>
                        </td>
                        <td style={cellStyle}>
                          {requirement.approved_test_count} / {requirement.draft_test_count} / {requirement.rejected_test_count}
                        </td>
                        <td style={cellStyle}>
                          <button
                            type="button"
                            aria-controls="saved-tests-panel"
                            aria-expanded={selectedRequirementId === requirement.requirement_id}
                            onClick={() => {
                              if (selectedRequirementId === requirement.requirement_id) {
                                setSelectedRequirementId(null);
                                return;
                              }
                              setSavedTests([]);
                              setTestErrors([]);
                              setTestsLoading(requirement.test_case_ids.length > 0);
                              setSelectedRequirementId(requirement.requirement_id);
                            }}
                            style={{ ...buttonStyle, background: "#ffffff", color: "#24634f", padding: "7px 10px", whiteSpace: "nowrap", fontSize: "12px" }}
                          >
                            {selectedRequirementId === requirement.requirement_id ? "Hide tests" : `View tests (${requirement.test_case_count})`}
                          </button>
                          <button
                            type="button"
                            disabled={generatingRequirementId !== null || savingDraft}
                            onClick={() => void handleGenerate(requirement)}
                            style={{ ...buttonStyle, display: "block", marginTop: "8px", padding: "7px 10px", whiteSpace: "nowrap", fontSize: "12px", opacity: generatingRequirementId !== null || savingDraft ? 0.6 : 1 }}
                          >
                            {generatingRequirementId === requirement.requirement_id ? "Generating..." : "Generate draft"}
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
            <button type="button" aria-expanded={showTraceability} aria-controls="traceability-panel"
              onClick={() => setShowTraceability((value) => !value)}
              style={{ ...buttonStyle, marginTop: "22px", background: "#ffffff", color: "#24634f" }}>
              {showTraceability ? "Hide traceability" : "Show traceability"}
            </button>
            <div id="traceability-panel">
              {showTraceability && <TraceabilityView coverage={coverage} onViewTests={(requirementId) => {
                setSelectedRequirementId(requirementId);
                document.getElementById("saved-tests-panel")?.scrollIntoView({ behavior: "smooth", block: "start" });
              }} />}
            </div>
            {(generatingRequirementId !== null || generatedDraft || generationError) && (
              <section style={{ marginTop: "28px" }} aria-labelledby="generated-draft-heading">
                <h3 id="generated-draft-heading" style={{ fontSize: "20px", fontWeight: 700 }}>
                  {generatingRequirementId ? `Generating draft for ${generatingRequirementId}` : generatedDraft ? `${savedDraftId ? "Saved test" : "Generated draft"} for ${generatedDraft.requirement_id}` : "Draft generation"}
                </h3>
                {generatingRequirementId && (
                  <p role="status" style={{ marginTop: "12px", color: "#596779", lineHeight: 1.6 }}>
                    Waiting for the local model. This may take a few minutes, especially on the first request.
                  </p>
                )}
                {generationError && (
                  <p role="alert" style={{ marginTop: "16px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>
                    {generationError}
                  </p>
                )}
                {generatedDraft && (
                  <>
                    {savedDraftId ? (
                      <p role="status" style={{ marginTop: "16px", padding: "14px", background: "#e7f5ed", color: "#17623b", borderRadius: "8px", overflowWrap: "anywhere" }}>
                        Saved test case ID: {savedDraftId}. {savedGeneratedDraft?.status === "approved" || savedGeneratedDraft?.status === "rejected" ? `Review status: ${savedGeneratedDraft.status}.` : "Status: draft. Use View tests to edit and review it."}
                      </p>
                    ) : (
                      <p style={{ marginTop: "12px", color: "#596779", fontSize: "13px", lineHeight: 1.6 }}>
                        This draft is not saved. Inspect its steps, expected result, and assumptions against the source.
                        Structure validation does not establish correctness. Refreshing the page or generating another draft replaces this preview.
                      </p>
                    )}
                    <button
                      type="button"
                      onClick={() => void handleSaveDraft()}
                      disabled={savingDraft || savedDraftId !== null}
                      style={{ ...buttonStyle, marginTop: "14px", opacity: savingDraft || savedDraftId !== null ? 0.6 : 1 }}
                    >
                      {savingDraft ? "Saving..." : savedDraftId ? "Test saved" : "Save draft"}
                    </button>
                    {saveError && (
                      <p role="alert" style={{ marginTop: "14px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{saveError}</p>
                    )}
                    {saveWarnings.map((warning, index) => (
                      <p key={index} role="status" style={{ marginTop: "14px", padding: "14px", background: "#fff3d6", color: "#765300", borderRadius: "8px" }}>{warning}</p>
                    ))}
                    {savedGeneratedDraft ? (
                      <TestDetails record={savedGeneratedDraft} documentTitle={coverage.title} />
                    ) : !savedDraftId ? (
                      <TestDetails record={generatedDraft} documentTitle={coverage.title} />
                    ) : null}
                  </>
                )}
              </section>
            )}

            {reviewMessage && <p role="status" style={{ marginTop: "22px", padding: "14px", background: "#e7f5ed", color: "#17623b", borderRadius: "8px" }}>{reviewMessage}</p>}
            {reviewWarning && <p role="status" style={{ marginTop: "14px", padding: "14px", background: "#fff3d6", color: "#765300", borderRadius: "8px" }}>{reviewWarning}</p>}
            <section id="saved-tests-panel" style={{ marginTop: "28px" }} aria-labelledby="saved-tests-heading">
              {selectedRequirement ? (
                <>
                  <div style={{ display: "flex", gap: "12px", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap" }}>
                    <h3 id="saved-tests-heading" style={{ fontSize: "20px", fontWeight: 700 }}>
                      Tests for {selectedRequirement.requirement_id}
                    </h3>
                    <button type="button" onClick={() => setSelectedRequirementId(null)} style={{ ...buttonStyle, background: "#ffffff", color: "#24634f", padding: "7px 12px", fontSize: "13px" }}>
                      Close details
                    </button>
                  </div>
                  <p style={{ marginTop: "10px", lineHeight: 1.6, color: "#596779" }}>{selectedRequirement.text}</p>
                  {testsLoading && <p role="status" style={{ marginTop: "18px" }}>Loading saved tests...</p>}
                  {testErrors.map((message, index) => (
                    <p key={index} role="alert" style={{ marginTop: "16px", padding: "14px", background: "#fde9e9", color: "#9d2929", borderRadius: "8px" }}>{message}</p>
                  ))}
                  {!testsLoading && selectedRequirement.test_case_ids.length === 0 && (
                    <p style={{ marginTop: "18px", padding: "20px", background: "#ffffff", border: "1px solid #e0e6ed", borderRadius: "10px" }}>
                      No saved tests are linked to this requirement yet.
                    </p>
                  )}
                  {!testsLoading && savedTests.map((record) => (
                    <TestDetails key={record.test_case_id} record={record} documentTitle={coverage.title} onUpdated={handleDraftUpdated} onReviewed={handleReviewed} />
                  ))}
                </>
              ) : (
                <p id="saved-tests-heading" style={{ color: "#596779", fontSize: "14px" }}>
                  Select View tests to inspect a test case and its source requirement.
                </p>
              )}
            </section>
          </section>
        )}
      </div>
    </main>
  );
}
